apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmanager-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  volumeMode: Filesystem
  awsElasticBlockStore:
    volumeID: vol-0e7aa8511ffae60cd  # Replace with your actual AWS EBS volume ID
    fsType: ext4

